name: Build APK from ZIP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip project
        run: |
          mkdir project
          unzip '*.zip' -d project
          cd project
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x project/gradlew

      - name: Build Release APK
        run: cd project && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ProtectYourself-APK
          path: project/app/build/outputs/apk/release/app-release.apk
